name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  win32-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Win32
        run: cmake -S . -B build -A Win32

      - name: Build Release
        run: cmake --build build --config Release --parallel

      - name: Upload ASI
        uses: actions/upload-artifact@v4
        with:
          name: resamp-by-cyzenn-03dl-win32
          path: build/Release/resamp++.asi
